[book]
authors = ["Roman Frołow"]
language = "pl-PL"
multilingual = false
src = "src"
title = "Nauka Ziga"
description = "Tłumaczenie oryginalnej książki opublikowanej przez Karla Seguina"

[output.html]
git-repository-url = "https://github.com/rofrol/learning-zig-karlseguin"
git-repository-icon = "fa-github"

[output.html.print]
enable = true # include support for printable output
page-break = true # insert page-break after each chapter

[output.html.search]
enable = true
